### ISSUE TITLE
Issues with unit tests using pytest

### ISSUE THREAD

**Issue by thisisjsimon** [thisisjsimon/SiteSniffer#4]
I have added unit tests using pytest to my project, but I am getting some errors. I used the URL 'https://www.python.org/' as an example, and I am encountering the following errors:

1. FAILED sitesniffer/tests/test_sitesniffer.py::test_ip_address - AssertionError: assert '146.75.116.223' == '151.101.2.223'
The IP address '146.75.116.223' is valid according to the test_valid_ip_address() function, but it does not match the correct IP address '151.101.2.223'. Also, when I connect to the internet using mobile data, ip_address() returns '2a04:4e42:8d::223', which causes the test_valid_ip_address() function to fail.

2. FAILED sitesniffer/tests/test_sitesniffer.py::test_is_mobile_friendly - AssertionError: assert True == False
3. FAILED sitesniffer/tests/test_sitesniffer.py::test_has_cookies - AssertionError: assert False == True
4. FAILED sitesniffer/tests/test_sitesniffer.py::test_has_google_analytics - AssertionError: assert False == True
According to some sources on the internet, the expected boolean values in the tests are correct, but I am still getting errors.

Lastly, I am having trouble with the following error:
5. FAILED sitesniffer/tests/test_sitesniffer.py::test_page_keywords - AssertionError: assert 'Python, programming language, documentation, community' in 'Python programming language object oriente...
Perhaps 'https://www.python.org/' is not an optimal URL for this function, as it has a large number of keywords. page_keywords() does not output all of them, and the test_page_keywords function does not include all of them, causing a difference between the expected and actual values.

Could you please assist me with resolving these issues? Thank you in advance.

**Comment by realshouzy** [comment]
Fixed it, take a look at my pull request!
